# -*- coding: utf-8 -*-
"""csvtest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ikm1jSBGusSMW3jdTiEUZplbRlmP2vs7
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/祥哥/testing.csv')

df

df.duplicated()

df.groupby('id')

df.groupby(by=['id'], sort=True)['class'].sum().values.tolist()

df2 = df.groupby('id').aggregate(lambda x: x.unique().tolist())
df2.groupby(by=['id'], sort=True)['class'].sum().values.tolist()

"""# 0311"""

tarin_data1 = pd.read_csv('/content/drive/MyDrive/祥哥/TrainingData_sesssion1.csv')

pd.set_option("display.max_rows", 2000)    #設定最大能顯示1000rows

df3 = tarin_data1.groupby('Sale_No').aggregate(lambda x: x.unique().tolist())
df3.groupby(by=['Sale_No'], sort=True)['Prod_No'].sum().values.tolist()